# Generated by Django 5.1.4 on 2026-06-11 20:16

import apps.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_id_label', models.CharField(max_length=120)),
                ('asset_class', models.CharField(blank=True, max_length=255)),
                ('supplier_cr', models.CharField(blank=True, max_length=20)),
                ('origin', models.CharField(blank=True, max_length=10)),
                ('local_or_foreign', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('FOREIGN', 'Foreign')], max_length=10)),
                ('annual_depreciation', apps.common.fields.EncryptedDecimalField()),
                ('operating_in_ksa', models.BooleanField(default=True)),
                ('included_in_score', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetRegisterUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_ref', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
