# Generated by Django 5.1.4 on 2026-06-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='assetregisterupload',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_registers', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='assetregisterupload',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assetregisterupload'),
        ),
    ]
