# Generated by Django 5.1.4 on 2026-06-11 20:16

import apps.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_field_name', models.CharField(max_length=255)),
                ('system_field', models.CharField(choices=[('INVOICE_NO', 'Invoice Number'), ('VAT', 'VAT Number'), ('GROSS', 'Gross Amount'), ('VAT_AMOUNT', 'VAT Amount')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('MANDATORY_FOREIGN', 'Mandatory item from Foreign vendor'), ('THRESHOLD', 'Below minimum LC threshold')], max_length=20)),
                ('etimad_code', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=120)),
                ('vat_number', models.CharField(blank=True, max_length=15)),
                ('gross_amount', apps.common.fields.EncryptedDecimalField()),
                ('vat_amount', apps.common.fields.EncryptedDecimalField()),
                ('net_eligible_spend', apps.common.fields.EncryptedDecimalField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('goods_or_services', models.CharField(blank=True, choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')], max_length=10)),
                ('local_or_foreign', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('FOREIGN', 'Foreign')], max_length=10)),
                ('factory_manufactured', models.BooleanField(default=False)),
                ('audited_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcMonthlyUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('raw_file_ref', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopVendorSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_vendor_ids', models.JSONField(default=list)),
                ('computed_lc_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('manual_override', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('cr_number', models.CharField(blank=True, max_length=20)),
                ('vat_number', models.CharField(blank=True, max_length=15)),
                ('classification', models.CharField(choices=[('LOCAL', 'Local Vendor'), ('FOREIGN', 'Foreign Vendor')], default='FOREIGN', max_length=10)),
                ('verified_lc_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('lc_score_source', models.CharField(choices=[('CERT', 'Parsed LCGPA Certificate'), ('GLOBAL_WHITELIST', 'Global Whitelist auto-fill'), ('BASELINE', 'Baseline (sector / expired)')], default='BASELINE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorLcgpaCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_ref', models.CharField(max_length=512)),
                ('parsed_vendor_name', models.CharField(blank=True, max_length=255)),
                ('parsed_cr_vat', models.CharField(blank=True, max_length=20)),
                ('parsed_lc_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('doc_ai_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
