# Generated by Django 5.1.4 on 2026-06-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('seed', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmapping',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='compliancewarning',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_warnings', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='compliancewarning',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='etimad_commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='seed.etimadcommodity'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='isic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='seed.isicsector'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='procmonthlyupload',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proc_uploads', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='procmonthlyupload',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.contract'),
        ),
        migrations.AddField(
            model_name='procmonthlyupload',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='procurement.procmonthlyupload'),
        ),
        migrations.AddField(
            model_name='topvendorselection',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_vendor_selections', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='topvendorselection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='global_whitelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='seed.globalwhitelistentry'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='compliancewarning',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='vendorlcgpacertificate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vendorlcgpacertificate',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='procurement.vendor'),
        ),
        migrations.AddConstraint(
            model_name='columnmapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'system_field'), name='uq_colmap_field'),
        ),
        migrations.AddConstraint(
            model_name='procmonthlyupload',
            constraint=models.UniqueConstraint(fields=('tenant', 'compliance_year', 'month'), name='uq_proc_upload_slot'),
        ),
    ]
