# Generated by Django 5.1.4 on 2026-06-11 20:16

import apps.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GosiCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_ref', models.CharField(max_length=512)),
                ('saudi_headcount', models.PositiveIntegerField(default=0)),
                ('expat_headcount', models.PositiveIntegerField(default=0)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HrMonthlyUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('payroll_file_ref', models.CharField(blank=True, max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', apps.common.fields.EncryptedCharField()),
                ('name', apps.common.fields.EncryptedCharField()),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('is_saudi', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VACATION', 'Vacation (0 SAR, counts for GOSI)')], default='ACTIVE', max_length=10)),
                ('classification', models.CharField(choices=[('REGULAR', 'Regular Employee'), ('TRAINEE', 'Trainee / Scholarship (-> Section 6)')], default='REGULAR', max_length=10)),
                ('basic', apps.common.fields.EncryptedDecimalField()),
                ('housing', apps.common.fields.EncryptedDecimalField()),
                ('transport', apps.common.fields.EncryptedDecimalField()),
                ('bonus_vacation_pay', apps.common.fields.EncryptedDecimalField()),
                ('eosb_accrual', apps.common.fields.EncryptedDecimalField()),
                ('section3_amount', apps.common.fields.EncryptedDecimalField(blank=True, null=True)),
                ('section6_amount', apps.common.fields.EncryptedDecimalField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
