# Generated by Django 5.1.4 on 2026-06-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gosicertificate',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.tenantbranch'),
        ),
        migrations.AddField(
            model_name='gosicertificate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='hrmonthlyupload',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_uploads', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='hrmonthlyupload',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='gosicertificate',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gosi_certs', to='hr.hrmonthlyupload'),
        ),
        migrations.AddField(
            model_name='payrollrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='payrollrow',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='hr.hrmonthlyupload'),
        ),
        migrations.AddConstraint(
            model_name='hrmonthlyupload',
            constraint=models.UniqueConstraint(fields=('tenant', 'compliance_year', 'month'), name='uq_hr_upload_slot'),
        ),
    ]
