# Generated by Django 5.1.4 on 2026-06-11 20:16

import apps.common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('is_paid', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked (post-certification)')], default='OPEN', max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_cr_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CR Number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('subscription_tier', models.CharField(choices=[('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'Hold (billing suspended)')], default='ACTIVE', max_length=10)),
                ('billing_status', models.CharField(choices=[('FULLY_PAID', 'Fully Paid'), ('PARTIAL_PAID', 'Partial Paid'), ('DELAYED', 'Delayed')], default='FULLY_PAID', max_length=15)),
                ('max_employees', models.PositiveIntegerField(default=0)),
                ('max_vendors', models.PositiveIntegerField(default=0)),
                ('hold_flag', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('paid_years', models.JSONField(default=list)),
                ('payment_status', models.CharField(choices=[('FULLY_PAID', 'Fully Paid'), ('PARTIAL_PAID', 'Partial Paid'), ('DELAYED', 'Delayed')], max_length=15)),
                ('hold_flag', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_name', models.CharField(max_length=255)),
                ('gov_entity', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cr_scope', models.CharField(blank=True, max_length=10)),
                ('compliance_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tenancy.complianceyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='complianceyear',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cr_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CR Number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('zatca_vat', models.CharField(max_length=15, validators=[apps.common.validators.zatca_vat_validator])),
                ('national_address_wasel', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='National Address (Wasel) must be 4 uppercase letters + 4 digits (e.g. RAGI2929).', regex='^[A-Z]{4}\\d{4}$')])),
                ('consolidates_multi_cr', models.BooleanField(default=False)),
                ('isic_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_profiles', to='seed.isicsector')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cr_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CR Number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('is_main', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='complianceyear',
            constraint=models.UniqueConstraint(fields=('tenant', 'year'), name='uq_year_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantbranch',
            constraint=models.UniqueConstraint(fields=('tenant', 'cr_number'), name='uq_branch_cr_per_tenant'),
        ),
    ]
