# Generated by Django 5.1.4 on 2026-06-11 20:16

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWhitelistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vat_number', models.CharField(max_length=15, unique=True)),
                ('cr_number', models.CharField(blank=True, max_length=10)),
                ('vendor_name_norm', models.CharField(db_index=True, max_length=512)),
                ('lc_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('certificate_expiry_date', models.DateField(blank=True, null=True)),
                ('financial_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_cert_sha256', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsicSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(blank=True, choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')], max_length=10)),
                ('baseline_lc_score', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('compliance_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MandatoryMinThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etimad_code', models.CharField(db_index=True, max_length=32)),
                ('year', models.PositiveSmallIntegerField()),
                ('min_pct', models.DecimalField(decimal_places=4, max_digits=5)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateCellMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_variable', models.CharField(max_length=120)),
                ('sheet_name', models.CharField(max_length=120)),
                ('cell_coordinate', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(choices=[('LC_SCORE_V2', 'Local Content Score Template v2'), ('TARGET_ENTITY', 'Target LC Score (Entity Level)'), ('TARGET_CONTRACT', 'Target LC Score (Contract Level)'), ('PERIODIC_CONTRACT', 'Periodic / Final Report (Contract Level)')], max_length=30)),
                ('compliance_year', models.PositiveSmallIntegerField()),
                ('file_ref', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtimadCommodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etimad_code', models.CharField(db_index=True, max_length=32)),
                ('segment_no', models.CharField(blank=True, max_length=32)),
                ('sector_sheet', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=512)),
                ('name_en', models.CharField(blank=True, max_length=512)),
                ('desc_ar', models.TextField(blank=True)),
                ('desc_en', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['etimad_code'], name='seed_etimad_etimad__5f0653_idx')],
                'constraints': [models.UniqueConstraint(fields=('etimad_code', 'sector_sheet'), name='uq_etimad_code_sheet')],
            },
        ),
    ]
