# Generated by Django 5.1.4 on 2026-06-11 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalwhitelistentry',
            name='_source_tenant',
            field=models.ForeignKey(blank=True, db_column='source_tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='mandatoryminthreshold',
            constraint=models.UniqueConstraint(fields=('etimad_code', 'year'), name='uq_threshold_code_year'),
        ),
        migrations.AddField(
            model_name='templatevault',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatecellmapping',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_mappings', to='seed.templatevault'),
        ),
        migrations.AddConstraint(
            model_name='templatevault',
            constraint=models.UniqueConstraint(fields=('template_key', 'compliance_year'), name='uq_template_key_year'),
        ),
    ]
