# Generated by Django 5.1.4 on 2026-06-11 20:16

import apps.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapexItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_cr', models.CharField(blank=True, max_length=20)),
                ('goods_or_services', models.CharField(blank=True, choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')], max_length=10)),
                ('local_or_foreign', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('FOREIGN', 'Foreign')], max_length=10)),
                ('factory_manufactured', models.BooleanField(default=False)),
                ('amount', apps.common.fields.EncryptedDecimalField()),
                ('audited_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
