# Generated by Django 5.1.4 on 2026-06-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capex', '0001_initial'),
        ('seed', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capexitem',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capex_items', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='capexitem',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.contract'),
        ),
        migrations.AddField(
            model_name='capexitem',
            name='isic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='seed.isicsector'),
        ),
        migrations.AddField(
            model_name='capexitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
    ]
