# Generated by Django 5.1.4 on 2026-06-11 20:16

import apps.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualHardClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenues', apps.common.fields.EncryptedDecimalField()),
                ('direct_costs', apps.common.fields.EncryptedDecimalField()),
                ('gna', apps.common.fields.EncryptedDecimalField()),
                ('selling_distribution', apps.common.fields.EncryptedDecimalField()),
                ('finance_costs', apps.common.fields.EncryptedDecimalField()),
                ('state', models.CharField(default='DRAFT', max_length=20)),
                ('reconciliation_passed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('FIN_STATEMENTS_PDF', 'Signed Financial Statements (PDF)'), ('TB_EXCEL', 'Raw Trial Balance (Excel)'), ('GOSI_PDF', 'GOSI Certificate (PDF)')], max_length=20)),
                ('file_ref', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlySoftClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('total_salaries', apps.common.fields.EncryptedDecimalField()),
                ('total_purchases', apps.common.fields.EncryptedDecimalField()),
                ('hr_variance', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('proc_variance', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual (Hard-Close)')], max_length=10)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TbAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(blank=True, max_length=64)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('mapped_category', models.CharField(choices=[('REVENUE', 'Revenue'), ('DIRECT_COST', 'Direct Cost'), ('GNA', 'G&A'), ('SELLING', 'Selling / Distribution'), ('FINANCE_COST', 'Finance Cost'), ('DEPRECIATION', 'Depreciation Expense'), ('EXEMPT_ZAKAT', 'Exemption — Zakat'), ('EXEMPT_CUSTOMS', 'Exemption — Customs & Duties'), ('EXEMPT_VISA', 'Exemption — Visa / Residency Fees')], max_length=20)),
                ('amount', apps.common.fields.EncryptedDecimalField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrialBalanceUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_file_ref', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
