# Generated by Django 5.1.4 on 2026-06-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualhardclose',
            name='compliance_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hard_close', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='annualhardclose',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='evidencevault',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='evidencevault',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='monthlysoftclose',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_closes', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='monthlysoftclose',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='reconciliationcheck',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='reconciliationcheck',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='tbaccountmapping',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='trialbalanceupload',
            name='compliance_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balances', to='tenancy.complianceyear'),
        ),
        migrations.AddField(
            model_name='trialbalanceupload',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='tbaccountmapping',
            name='trial_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='finance.trialbalanceupload'),
        ),
        migrations.AddConstraint(
            model_name='monthlysoftclose',
            constraint=models.UniqueConstraint(fields=('tenant', 'compliance_year', 'month'), name='uq_soft_close_slot'),
        ),
    ]
