# Generated by Django 5.1.4 on 2026-06-11 20:16

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=12)),
                ('content', models.TextField()),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('category', models.CharField(choices=[('LCGPA', 'LCGPA'), ('ZATCA', 'ZATCA'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('PROCUREMENT', 'Procurement')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LCGPA', 'LCGPA'), ('ZATCA', 'ZATCA'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('PROCUREMENT', 'Procurement')], max_length=20)),
                ('is_global', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
