# Generated by Django 5.1.4 on 2026-06-11 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SCORE_XLSX', 'LC Score .xlsx'), ('TARGET_XLSX', 'Target .xlsx'), ('PERIODIC_XLSX', 'Periodic/Final .xlsx'), ('AUDIT_PACK_ZIP', 'Audit Pack .zip')], max_length=20)),
                ('file_ref', models.CharField(max_length=512)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LcReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('ENTITY', 'Entity Level'), ('CONTRACT', 'Contract Level')], max_length=10)),
                ('type', models.CharField(choices=[('TARGET', 'Target LC Score'), ('PERIODIC', 'Periodic Report'), ('FINAL', 'Final Report'), ('SCORE', 'LC Score')], max_length=10)),
                ('state', models.CharField(default='DRAFT', max_length=20)),
                ('computed_score', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulatorScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('SUPERADMIN', 'Super Admin (cross-company)'), ('PROCUREMENT', 'Procurement (supply chain)'), ('HR', 'HR (Saudization)')], max_length=12)),
                ('inputs', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
